add_subdirectory(detail)
add_library(storeintf INTERFACE)
target_include_directories(storeintf INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(storeintf INTERFACE storedetail infra_status)
add_subdirectory(nfsstore)
add_subdirectory(pcstore)
add_subdirectory(ds3fs)
add_subdirectory(posix)
add_subdirectory(compress)
add_subdirectory(cache)
if(RUNTIME_ENVIRONMENT STREQUAL "ascend" OR RUNTIME_ENVIRONMENT STREQUAL "simu")
    add_subdirectory(dram)
endif()
if(BUILD_UCM_ASU)
    add_subdirectory(asu)
    add_subdirectory(delegator)
endif()
add_subdirectory(empty)
add_subdirectory(fake)
add_subdirectory(mooncakestore)
add_subdirectory(pipeline)
add_subdirectory(test)
