set(ASCEND_ROOT "/usr/local/Ascend/ascend-toolkit/latest" CACHE PATH "Path to Ascend root directory")
add_library(Ascend::ascendcl UNKNOWN IMPORTED)
set_target_properties(Ascend::ascendcl PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${ASCEND_ROOT}/include"
    IMPORTED_LOCATION "${ASCEND_ROOT}/lib64/libascendcl.so"
)
add_library(trans STATIC
    ascend_device.cc
    ascend_buffer.cc
    ascend_event.cc
    ascend_stream.cc
)
if(ASCEND_SUPPORTS_REGISTER_PIN)
    target_compile_definitions(trans PRIVATE ASCEND_SUPPORTS_REGISTER_PIN=1)
endif()
target_link_libraries(trans PUBLIC
    fmt
    Ascend::ascendcl
)
