#ifndef KVSTAR_RETRIEVE_CLIB_TASK_STATUS_H
#define KVSTAR_RETRIEVE_CLIB_TASK_STATUS_H

namespace KVStar {
    enum class TaskStatus { PENDING, RUNNING, SUCCESS, FAILURE };
}

#endif //KVSTAR_RETRIEVE_CLIB_TASK_STATUS_H
