# Set to other image if needed
ARG IMAGE_SOURCE="lmsysorg"
ARG IMAGE_NAME_VERSION="sglang:v0.5.5.post3"

FROM ${IMAGE_SOURCE}/${IMAGE_NAME_VERSION}

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG INSTALL_MODE="source"

WORKDIR /workspace

# Install unified-cache-management
COPY . /workspace/unified-cache-management

RUN pip config set global.index-url ${PIP_INDEX_URL}

# Build or link package
RUN if [ "${INSTALL_MODE}" != "package" ]; then \
        pip install --no-cache-dir build cmake && \
        export WORKSPACE=/workspace SKIP_TAR=1 && \
        bash /workspace/unified-cache-management/scripts/build_sglang.sh; \
    else \
        ln -s /workspace/unified-cache-management /workspace/package; \
    fi

# Install UCM
RUN pip install /workspace/package/uc_manager-*.whl

# Apply patch for SGLang
RUN cd /sgl-workspace/sglang \
    && git apply /workspace/package/sglang-adapt.patch

ENTRYPOINT ["/bin/bash"]
