# Set to other image if needed
ARG IMAGE_SOURCE="swr.cn-south-1.myhuaweicloud.com/ascendhub"
ARG IMAGE_NAME_VERSION="mindie:2.3.0-800I-A2-py311-openeuler24.03-lts"

FROM ${IMAGE_SOURCE}/${IMAGE_NAME_VERSION}

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG UCM_ENABLE_MINDIE=1
ARG UCM_CXX11_ABI=1
ARG INSTALL_MODE="source"

WORKDIR /workspace

# Install unified-cache-management
COPY . /workspace/unified-cache-management

RUN pip config set global.index-url ${PIP_INDEX_URL}

ENV PLATFORM=ascend \
    UCM_ENABLE_MINDIE=${UCM_ENABLE_MINDIE} \
    UCM_CXX11_ABI=${UCM_CXX11_ABI}

# Build or link package
RUN if [ "${INSTALL_MODE}" != "package" ]; then \
        pip install --no-cache-dir build cmake && \
        export WORKSPACE=/workspace SKIP_TAR=1 && \
        bash /workspace/unified-cache-management/scripts/build_mindie.sh; \
    else \
        ln -s /workspace/unified-cache-management /workspace/package; \
    fi

# Install UCM
RUN pip install /workspace/package/uc_manager-*.whl

# Apply patch for MindIE
RUN UCM_ENABLE_MINDIE=${UCM_ENABLE_MINDIE} python -c "import ucm.integration.mindie.patch.boot_patch as bp; bp.apply_patch(); print('[UCM][MindIE] patch applied (or already in place).')"

ENTRYPOINT ["/bin/bash"]
