# UCM Configuration File Example
# 
# This file demonstrates how to configure UCM using YAML.
# You can use this config file by setting the path to this file in kv_connector_extra_config in launch script or command line like this:
# kv_connector_extra_config={"UCM_CONFIG_FILE": "/workspace/unified-cache-management/examples/ucm_config_example.yaml"}
#
# Alternatively, you can still use kv_connector_extra_config in KVTransferConfig
# for backward compatibility.

# Connector name (e.g., "UcmNfsStore", "UcmPipelineStore")
# Default cache_buffer_capacity_gb for CacheStore is 256GB.When use models like MLA you should make sure that /dev/shm has enough space, or you can set this parameter to a smaller value.
# One important detail is that when multiple DP instances run on the same node, each of them creates its own CacheStore.
ucm_connectors:
  - ucm_connector_name: "UcmPipelineStore"
    ucm_connector_config:
      store_pipeline: "Cache|Posix"
      storage_backends: "/mnt/test"
      io_direct: false
      # cache_buffer_capacity_gb: 256
      # posix_capacity_gb: 1024

# When you use UcmNfsStore, you should set enable_event_sync to false.
enable_event_sync: true
# Enable UCM metrics so they can be monitored online via Grafana and Prometheus.
# metrics_config_path: "/workspace/unified-cache-management/examples/metrics/metrics_configs.yaml"

# Sparse attention configuration
# ucm_sparse_config:
  # GSAOnDevice: {}


# Whether to use layerwise loading/saving (optional, default: True for UCMConnector)
use_layerwise: true
# hit_ratio: 0.9

# Whether to record requests' traces (optional, default: False)
# When enable_record_traces set to true, logs per-request traces (timestamp, input_length, output_length, hash_ids)
# Each hash_id takes 32 bytes. Enable only when needed with proper UCM_LOG_MAX_FILES and UCM_LOG_MAX_SIZE.
enable_record_traces: false

# Whether to use UCM Lite Connector (optional, default: False)
# UCM Lite Connector is used with Fake Store to skip actual KV dump and load operations, only for request hit ratio statistics. 
# It is suggested to collect hit ratio statistics and confirm with relevant project members whether to adopt UCM.
use_lite: false

# Minimum token threshold for KV persistence.
# Requests with fewer tokens skip KV load and dump operations.
persist_token_threshold: 0
